name: CI

on:
  pull_request:
    branches: ["*"]
    types: [opened, synchronize, reopened, edited, closed] # <--- **IMPORTANT** to subscribe to these events // https://drift.trpc.io/docs/github
  push:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  generate-prisma-client:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-keys.outputs.key }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./tooling/github/setup

      - name: Generate Prisma Client
        run: pnpm turbo db:generate

      - name: Get Cache Key
        id: cache-keys
        run: echo "::set-output name=key::$(date +%s)"

      - name: Cache Prisma Client
        uses: actions/cache@v3
        with:
          path: |
            node_modules/.prisma/client
          key: ${{ steps.cache-keys.outputs.key }}
  lint:
    needs: generate-prisma-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Cache Prisma Client
        uses: actions/cache@v3
        with:
          path: |
            node_modules/.prisma/client
          key: ${{ needs.generate-prisma-client.outputs.cache-key }}

      - name: Copy env
        shell: bash
        run: cp .env.example .env

      - name: Lint
        run: pnpm lint && pnpm lint:ws
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Format
        run: pnpm format
  typecheck:
    needs: generate-prisma-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Cache Prisma Client
        uses: actions/cache@v3
        with:
          path: |
            node_modules/.prisma/client
          key: ${{ needs.generate-prisma-client.outputs.cache-key }}

      - name: Typecheck
        run: turbo typecheck

  upload-drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Upload Drift
        run: cd packages/api && pnpm trpc upload -vv # optional: -vv for verbose output
        env:
          API_KEY: ${{ secrets.DRIFT_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
